/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "Hono": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "LookupServiceUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwoCaptchaApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TwoCaptchaProxyUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
